import Foundation

/// Usage: EmbedResourcesTool <output.swift> <directory>...
/// Every .metal, .h and .json file in the given directories is emitted as a
/// raw string literal keyed by "<directory name>/<file name>".
let arguments = CommandLine.arguments
guard arguments.count >= 3 else {
    FileHandle.standardError.write(Data("usage: EmbedResourcesTool <output.swift> <directory>...\n".utf8))
    exit(64)
}
let output = arguments[1]
let allowed: Set<String> = ["metal", "h", "json"]
var entries: [(key: String, text: String)] = []
for directory in arguments.dropFirst(2) {
    let base = URL(fileURLWithPath: directory)
    let names = (try? FileManager.default.contentsOfDirectory(atPath: directory)) ?? []
    for name in names.sorted() where allowed.contains((name as NSString).pathExtension) {
        let text = try String(contentsOf: base.appendingPathComponent(name), encoding: .utf8)
        entries.append((key: "\(base.lastPathComponent)/\(name)", text: text))
    }
}
var source = "// Generated by EmbedResourcesTool at build time. Do not edit.\n\n"
source += "enum EmbeddedResources {\n    static let files: [String: String] = [\n"
for entry in entries {
    source += "        \"\(entry.key)\": #####\"\"\"\n"
    source += entry.text
    source += "\n\"\"\"#####,\n"
}
source += "    ]\n}\n"
try source.write(toFile: output, atomically: true, encoding: .utf8)
